services:
  api:
    build:
      context: .
      dockerfile: TaskService.Api/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      - Mongo__ConnectionString=mongodb://mongo:27017
      - Mongo__Database=TaskDb

  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
